version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    labels:
      - dependencies
      - actions
      - Skip Changelog
    commit-message:
      prefix: "chore: "
    schedule:
      interval: weekly
      day: sunday
  - package-ecosystem: docker
    directory: /
    labels:
      - dependencies
      - docker
      - Skip Changelog
    commit-message:
      prefix: "chore: "
    schedule:
      interval: weekly
      day: sunday
  - package-ecosystem: gomod
    directory: /
    labels:
      - dependencies
      - go
      - Skip Changelog
    commit-message:
      prefix: "chore: "
    schedule:
      interval: daily
