name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - .github/**
      - docs/**
      - LICENSES/**
      - README.md
      - mkdocs.yaml
  workflow_run:
    workflows: [CI]
    types: [completed]
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' || github.event_name == 'push' || github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ">=1.19.0"
          check-latest: true
          cache: true

      - name: Create Helm Compose Distributions
        run: make dist

      - uses: actions/upload-artifact@v3
        with:
          name: helm-compose
          path: release/*

      - name: Publish release
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          for FILE in release/*.tgz; do 
            gh release upload ${TAG} ${FILE} --clobber
          done

          gh release edit ${TAG} --draft=false
