on:
  workflow_dispatch:
  workflow_run:
    workflows: [CI]
    types: [completed]
    branches: [main]

name: CD

jobs:
  cd:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ">=1.19.0"
          check-latest: true
          cache: true
      - name: Create Helm Compose Distributions
        run: make dist
      - uses: actions/upload-artifact@v3
        with:
          name: helm-compose
          path: release/*
