on:
  push:
    branches:
      - main
      - workflows
  pull_request:
    branches:
      - main

name: CI

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ">=1.19.0"
          check-latest: true
          cache: true
      - uses: azure/setup-helm@v3
        with:
          version: v3.11.0
      - uses: helm/kind-action@v1.5.0
      - run: make install
      - run: helm compose install -f testdata/helm-compose.yaml
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ env.GITHUB_REF_NAME }}-${{ env.GITHUB_RUN_NUMBER }}
          path: |
            bin/compose
            plugin.yaml
