on:
  push:
    branches:
      - main
      - workflows
  pull_request:
    branches:
      - main

name: CI

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ">=1.19.0"
          check-latest: true
          cache: true
      - uses: azure/setup-helm@v3
      - run: make install
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: helm/kind-action@v1.5.0
      - run: helm compose install -f testdata/helm-compose.yaml
